apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pacman-pipeline
spec:
  params:
    - default: 'https://github.com/lmt-cbs/pacman-kikd.git'
      name: GIT_REPO
      type: string
    - default: main
      name: GIT_REVISION
      type: string
    - default: quay.io/lmtbelmonte01/pacman-kikd
      name: DESTINATION_IMAGE
      type: string
    - default: .
      name: CONTEXT_DIR
      type: string
    - default: 'https://github.com/lmt-cbs/pacman-kikd-manifests.git'
      name: CONFIG_GIT_REPO
      type: string
    - default: main
      name: CONFIG_GIT_REVISION
      type: string
  tasks:
    - name: fetch-repo
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: deleteExisting
          value: "true"
      taskRef:
        name: git-clone
      workspaces:
      - name: output
        workspace: app-source
    - name: build-app
      params:
        - name: GOALS
          value:
          - clean
          - package
        - name: CONTEXT_DIR
          value: $(params.CONTEXT_DIR)
      runAfter:
        - fetch-repo
      taskRef:
        name: maven
      workspaces:
        - name: maven-settings
          workspace: maven-settings
        - name: source
          workspace: app-source
    - name: build-push-image
      params:
        - name: IMAGE
          value: $(params.DESTINATION_IMAGE)
      runAfter:
        - build-app
      taskRef:
        name: buildah
      workspaces:
        - name: source
          workspace: app-source
    - name: git-update-deployment
      params:
      - name: GIT_REPOSITORY
        value: $(params.CONFIG_GIT_REPO)
      - name: NEW_IMAGE
        value: $(params.DESTINATION_IMAGE)
      - name: NEW_DIGEST
        value: $(tasks.build-push-image.results.IMAGE_DIGEST)
      - name: KUSTOMIZATION_PATH
        value: env/dev
      - name: GIT_REF
        value: $(params.CONFIG_GIT_REVISION)
      runAfter:
        - build-push-image
      taskRef:
        kind: Task
        name: git-update-deployment
      workspaces:
      - name: workspace
        workspace: app-source  
  workspaces:
     - name: app-source
     - name: maven-settings
