apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: greeter-eventlistener
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
  - bindings:
    - ref: greeter-triggerbinding
    template:
      ref: greeter-triggertemplate
