apiVersion: v1
kind: Service
metadata:
  labels:
    app: tekton-greeter
  name: tekton-greeter
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30007
  selector:
    app: tekton-greeter