apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: tekton-greeter-pipeline-hub-run-
spec:
  params:
    - name: GIT_REPO
      value: 'https://github.com/lmt-cbs/tekton-tutorial-greeter.git'
    - name: GIT_REF
      value: master
    - name: DESTINATION_IMAGE
      value: 'quay.io/lmtbelmonte01/tekton-greeter-pipeline:latest'
    - name: CONTEXT_DIR
      value: 'quarkus'  
    - name: IMAGE_DOCKERFILE
      value: 'quarkus/Dockerfile'    
    - name: IMAGE_CONTEXT_DIR
      value: 'quarkus'      
    - name: SCRIPT
      value: >
        kubectl create deploy tekton-greeter --image=quay.io/lmtbelmonte01/tekton-greeter-pipeline:latest
  pipelineRef:
    name: tekton-greeter-pipeline-hub
  serviceAccountName: tekton-deployer-sa
  workspaces:
    - name: maven-settings
      emptyDir: {}
    - name: app-source
      persistentVolumeClaim:
        claimName: app-source-pvc  
  podTemplate:
    securityContext:
      fsGroup: 65532